---
title: "Dem_Eco(5-7)"
format: html
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(313)
options (warn = -1)
setwd("/Users/zhumeng/Desktop/project/Dem_Eco/code")
# package loading
library(pacman)
p_load(
    mirt,
    kableExtra,
    psych, #KMOtest
    mediation,
    MASS,
    car,
    here,
    glue,
    tidyverse,
    stargazer,
    dotwhisker,
    modelsummary
)
```

# Some data

```{r dataLoad}
# IV
#wvs_pr <- readRDS("/Users/zhumeng/Documents/GitHub/Dems/data/IV_bayesian/stan_procedual.rds") 
#wvs_pe <- readRDS("/Users/zhumeng/Documents/GitHub/Dems/data/IV_bayesian/stan_performance.rds") 


# wvs
load("../data/WVST.rdata")
wvs <- WVS_TimeSeries_1981_2022_spss_v3_0 %>%
  filter(., S020 %in% 2005:2022) %>%
  dplyr::select(
   S002VS,
   S020,
   S003,
   S017,
   COUNTRY_ALPHA,
   COW_ALPHA,
   COW_NUM,
   E001,
   E003,
   E005,
   E224,
   E225,
   E226,
   E227,
   E228,
   E229,
   E230,
   E231,
   E232,
   E233,
   E233A,
   E233B,
   E234,
   E235,
   E236,
   F118,
   F119,
   F120,
   F121,
   F122,
   F123,
   F135A,
   E114,
   E116,
   E117,
   E117B)

wvs$wave <- wvs$S002VS #波次命名
wvs$wt <- wvs$S017 #权重
wvs$year <- wvs$S020 #年份命名
wvs$Country <- wvs$COUNTRY_ALPHA
wvs$country <- wvs$COW_ALPHA
wvs$cowCode<- wvs$COW_NUM
wvs$countryCode <- wvs$S003 #国家命名
wvs[wvs < 0] <- NA 

```

## IV

```{r IV}
## 民主的基本特征
wvs$rich_tax <- wvs$E224 #政府向富人征税补贴穷人
wvs$regilous <- wvs$E225 #宗教当局拥有法律最终解释权
wvs$election <- wvs$E226 #自由选择领导人
wvs$unempolyment_aid <- wvs$E227 #国家救济失业人员
wvs$army <- wvs$E228 #军队接管无能政府
wvs$protection <- wvs$E229 #公民权利免受国家压迫
wvs$inc_euqal <- wvs$E233A #国家需要促进收入平等
wvs$obey <- wvs$E233B #人们服从领导人
wvs$women_right <- wvs$E233 #妇女与男子享有同等权利
wvs$demo_importance <- wvs$E235 #认为民主的重要性 importance of
```

## CV

```{r CV}
ctr <- read.csv("/Users/zhumeng/Documents/GitHub/Dems/data/covs/dem_mood_apsr.csv") %>%
  dplyr::select(
    "COW_code",
    "Year",
    "lnGDP_imp",
    "lnGDP_m1",
    "GDP_cp_btw",
    "GDP_cp_within",
    "Corrup_TI_z",
    "Corrup_TI_m1",
    "Corrup_within",
    "Corrup_btw", 
    "Gini_SWIID",
    "Educ_yrs_UN",
    "Educ_yrs_m1",
    "Gini_m1"
  ) %>%
  rename(
    cowCode = COW_code,
    year = Year
  ) %>%
  filter(., year %in% 2005:2017)
  

full_data <- left_join(wvs,ctr,
                       by = c("cowCode","year"))
```

## panel data

```{r}

full_data$performance <- select(full_data,rich_tax, unempolyment_aid, inc_euqal) %>%
  rowMeans(na.rm = TRUE)
full_data$procedural <- select(full_data, election, protection,women_right) %>%
  rowMeans(na.rm = TRUE)

temp <- full_data %>%
  filter(!is.na(procedural) | !is.na(performance)) %>%
  group_by(wave, country) %>%
  summarise(
    performanceC = weighted.mean(performance, w = wt, na.rm = TRUE),
    proceduralC = weighted.mean(procedural, w = wt, na.rm = TRUE)
  )

full_data <- left_join(full_data,temp,by = "country")

rm(temp)

```

## regression

```{r regression}
#  ols regression
m1 <- lm(lnGDP_m1 ~ performanceC + proceduralC + as.factor(Country), data = full_data)
msummary(m1,output="gt", stars = TRUE)

# plm regression

library(plm)
datap <- pdata.frame(full_data, index = c("Country", "wave"))
datasp <- datap[order(datap$wave), ]



```

# Total data(可以不看)

```{r dataClean2}
#| echo = False
#| eval = False

wvs$year <- wvs$S020#年份命名
wvs$countryCode <- wvs$S003 #国家命名
wvs$countryN <- wvs$COUNTRY_ALPHA
wvs$cowN<- wvs$COW_NUM
wvs$Country <- wvs$COW_ALPHA
wvs$wt <- wvs$S017
wvs[wvs < 0] <- NA #将不符合问卷选项的回答标记为NA


# Personal character
wvs$sex_X001 <- wvs$X001 - 1 #性别
wvs$birth_X002 <- wvs$Q261 #出生年
wvs$age_X003 <- wvs$X003 #年龄
wvs$rural_X050C <- wvs$X050C - 1 #(1:urban 2:rural)
wvs$immigration_G027A <- wvs$G027A - 1 #是否出生在这个国家还是移民(1:本地人；2:移民)
wvs$marriage_X007 <- if_else(wvs$X007 == 1, 1, 0) # 婚姻情况(1:已婚 2:像结婚一样生活在一起 3:离婚 4:分居 5:丧偶 6:单身)
wvs$edu_X025A_01 <- wvs$X025A_01 #教育水平(原始数据0-8)
wvs$eduR_X025R <- wvs$X025R #教育水平（重新划分为1-3）
wvs$party_A068 <- wvs$A068 #党派成员
wvs$party_A068[wvs$party_A068 == '1|2'] <- 1 #将活跃和不活跃的都变成是否
wvs$jobSector_X052 <- wvs$X052 #(1:goverment 2:private sector 3:NGO)
wvs$socialLevel_X045 <- wvs$X045#(1:upper 2:upper middle 3:lower meddle 4:working 5:lower)
wvs$incomeLevel_X047 <- wvs$X047_WVS #(家庭收入属于哪一类群体 1:低收入 10:高收入)
wvs$reilious_F025 <- wvs$F025#将属于新教和天主教的教徒单独编码 新教伦理与资本主义精神
wvs$race_X051 <- wvs$X051 #(种族 1:白人 2:黑人 3:南亚印第安人 4:中国/日本等东亚黄种人 5:阿拉伯/中亚 6:其他)
# !种族这里的编码好像不对，记得去看数据
wvs$generation <- case_when(
  wvs$X002 < 1950 ~ "Founding Time",
  wvs$X002 >= 1950 & wvs$Q261 < 1966 ~ "Before Cultural Revolution",
  wvs$X002 >= 1966 & wvs$Q261 < 1978 ~ "Cultural Revolution",
  wvs$X002 >= 1978 ~ "Reform and Opening-Up",
  TRUE ~ as.character(wvs$Q261)
) %>%
  factor(levels = c(
    "Founding Time",
    "Before Cultural Revolution",
    "Cultural Revolution",
    "Reform and Opening-Up"
  )) #这一列主要对中国居民进行编码


# Happyness 模块2 生活满意度
wvs$happy_A170 <- wvs$A170 #你对你的整个生活有多满意？ 使用这张卡，其中1表示你“完全不满意”，10 表示你“完全满意”
wvs$happyT_E277 <- Recode(wvs$E277,"2 = 0; 3 = 1; 1 = 2") #生活水平的代际差异：比较你的生活水平和你父母在你这个年龄时的生活水平，你会说你的生活更好，更糟，还是差不多？ （1:更好; 2:更糟糕;3:差不多）

# socailCapital and socialTrust 模块3 社会信任

wvs$trustCom_A165 <- wvs$A165 #一般来说，您认为大多数人是可以信任的，还是和人相处要越小心越好
wvs$trustFam_D001_B <- 5-wvs$D001_B #请问您对家人是非常信任、比较信任、不太信任，还是非常不信任
wvs$trustNei_G007_18_B <- 5-wvs$G007_18_B #请问您对熟人是非常信任、比较信任、不太信任，还是非常不信任
wvs$trustArmy_E069_02 <- 5-wvs$E069_02 #对军队的信任度如何
wvs$trustPolice_E069_06 <- 5-wvs$E069_06 #对警察的信任度如何
wvs$trustCourt_E069_17 <- 5-wvs$E069_17 #对法院的信任度如何
wvs$trustGoverment_E069_11 <- 5-wvs$E069_11 #对政府的信任度如何
wvs$trustParty_E069_12 <- 5-wvs$E069_12 #对政党的信任度如何
wvs$trustParliament_E069_07 <- 5-wvs$E069_07 #对人民代表大会的信任度如何

# economy values
wvs$incomeE_E035 <- wvs$E035 # 应该鼓励收入平等还是收入差距(income equal vs large income difference)
wvs$ownership_E036 <- wvs$E036 # 应该提高私有制还是国有制(private vs state/government ownership of business)
wvs$responsibility_E037 <- wvs$E037 # 人们应该承担更多的责任来自给自足还是政府应承担更多责任以确保每个人都有
wvs$competition_E039 <- wvs$E039 #竞争是好的还是坏的（越靠近1认为越好）
wvs$work_E040 <- wvs$E040 # 努力工作vs运气 的重要性（越靠近1认为努力工作越重要）
wvs$priority_B008 <- wvs$B008 # 经济增长和环境谁优先（1:环境重要 2：经济增长重要 3:其他）

# corruptuion
wvs$corPer_E268 <- wvs$E268 # 是否存在腐败(1:不存在；10:腐败严重)
wvs$corState_E269 <- wvs$E269 #您认为中央政府机关有多少人卷入了腐败(1:没有; 2: 少部分人；3: 大多数人 4: 所有人 )
wvs$corBusi_E270 <- wvs$E270 # 商务部门主管(business executives)有多少人卷入了腐败
wvs$corLocal_E271 <- wvs$E271 #您认为地方政府机关有多少人卷入了腐败
wvs$corPublic_E272 <- wvs$E272 #您认为公共服务机构(police/civil servants/ doctor/teachers)有多少人卷入了腐败
wvs$corMedia_E273 <- wvs$E273 # 您认为记者/媒体有多少人卷入了腐败
wvs$corrisk_E276 <- wvs$E276 # 在这个国家，因提供或收受贿赂、礼物或好处以换取公共服务而被追究责任的风险有多大？ 为了表达您的意见，请使用 10 分制，其中“1”表示“完全没有风险”，“10”表示“非常高风险”。

# migration 
wvs$immiDev_G052 <- wvs$G052 #移民对发展的影响(5:very good vs 1：very bad)

# security
wvs$security_H001 <- 5 - wvs$H001 # 安全感知(1:非常安全；4：一点都不安全)
wvs$freedom_equal_H008_07 <- wvs$H008_07 # 自由和平等谁更重要(1:自由；2：平等)
wvs$freedom_security_H008_08 <- wvs$H008_08 # 自由和安全谁更重要(1:自由；2: 安全)
wvs$nationlity_E012 <- wvs$E012 # 是否愿意为国家而战(1:yes; 2:no)


#  postmateralist value  后物质主义价值观
wvs$aimF_E001 <- wvs$E001 # 未来十年国家的发展目标1(第一选择 1:高水平经济增长；2:强大国防；3:人们在公共事务中有更多话语权；4:努力建设美丽的城市和乡村。1&2是物质主义价值观，3&4是后物质主义价值观)
wvs$aimS_E002 <- wvs$E002 # 未来十年国家的发展目标1(第二选择)
wvs$aimF_E003 <- wvs$E003 # 未来十年国家的发展目标2(第一选择 1:维护国家秩序；2:人们在政府决策中有更多的发言权；3:打击物价上涨；4:保护言论自由 1&3是物质主义价值观)
wvs$aimS_E004 <- wvs$E004 # 未来十年国家的发展目标2(第二选择)
wvs$aimF_E005 <- wvs$E005 # 未来十年国家的发展目标3(第一选择 1:稳定经济；2:构建更人性化的社会；3:构建观念比财富更重要的社会；4:打击犯罪 1&4是物质主义)
wvs$aimS_E006 <- wvs$E006 # 未来十年国家的发展目标3(第二选择)


# religious value 宗教价值观
wvs$god_F063 <- wvs$F063 # 上帝的重要性(1:一点也不重要 10:很重要)

# ethical value 道德价值观(这里包含伦理价值观的测量) socialTolerance
wvs$toleranceHomo_F118 <- wvs$F118 #hemosexcuality 同性恋 （1:不赞同 10:永远赞同）
wvs$tolerancePros_F119 <- wvs$F119 #prostitution 卖淫
wvs$toleranceAbor_F120 <- wvs$F120 # abortion 堕胎
wvs$toleranceDivo_F121 <- wvs$F121 # divorce 离婚
wvs$toleranceSexb_F135A <- wvs$F135A #sex before marriage 婚前性行为
wvs$toleranceSuic_F123 <- wvs$F123 #suicide 自杀
wvs$toleranceEuth_F122 <- wvs$F122 #Euthanasia 安乐死
wvs$tolerancePena_F144_02 <- wvs$F144_02 # death penalty 死刑

# political culture and regimes
wvs$sysLead_E114 <- 5 -wvs$E114 # 有一个不必为议会选举的强大领导人(1:very good 4:very bad 所以用5减 反向赋值)
wvs$sysArmy_E116 <- 5 - wvs$E116 # 有军队统治
wvs$sysDemo_E117 <- 5 - wvs$E117 # 拥有民主的政治体系
wvs$sysRegi_E117B <- 5 - wvs$E117B # 由不需要政党或选举的宗教法律管辖的制度
#wvs$sysPerf_q252 <- wvs$Q252 #（好像没有这个问题 #对当前政治体系/制度表现的满意度 satisfaction with the political performrance
wvs$indiviRight_E123 <- 5 - wvs$E123 #对人权的尊重(反向赋值后 越高越尊重)
wvs$prideNation_G006 <- 5- wvs$G006 #国家自豪感


## 民主的基本特征
wvs$demoTax_E224 <- wvs$E224 #政府向富人征税补贴穷人
wvs$demoRegilous_E225 <- wvs$E225 #宗教当局拥有法律最终解释权
wvs$demoSelect_E226 <- wvs$E226 #自由选择领导人
wvs$demoAid_E227 <- wvs$E227 #国家救济失业人员
wvs$demoArmy_E228 <- wvs$E228 #军队接管无能政府
wvs$demoCivil_E229 <- wvs$E229 #公民权利免受国家压迫
wvs$demoEquality_E233A <- wvs$E233A #国家需要促进收入平等
wvs$demoObey_E233B <- wvs$E233B #人们服从领导人
wvs$demoWomen_E233 <- wvs$E233 #妇女与男子享有同等权利
wvs$demoImportance_E235 <- wvs$E235 #认为民主的重要性 importance of democracy
wvs$demoLevel_E236 <- wvs$E236 #国家的民主水平


# political interest and participation 政治兴趣与政治参与
wvs$polityInt_E023 <- wvs$E023 #对政治感兴趣的程度(1:非常感兴趣；4:一点都不感兴趣)
wvs$polityDis_A062 <- wvs$A062 #讨论政治事件的频率(1:经常；2:偶尔；3:从不)
```
